# Chapter 5. UI 컴포넌트 테스트
### 5.7 비동기 처리가 포함된 UI zjavhsjsxm xptmxm
> Fetch API 로 전송하려면?

<br/>

### 5.7.1 테스트할 UI 컴포넌트
> 계정 정보 등록 페이지를 표시하는 컴포넌트

```shell
웹 API 응답 > postResult 에 메시지 저장 > 표시
Form 컴포넌트는 onSubmit 이벤트 발생 시 다음 함수 실행
```

```ts
import { useState } from "react";
import { Form } from "../06/Form";
import { postMyAddress } from "./fetchers";
import { handleSubmit } from "./handleSubmit";
import { checkPhoneNumber, ValidationError } from "./validations";

export const RegisterAddress = () => {
  const [postResult, setPostResult] = useState("");
  return (
    <div>
      <Form
        onSubmit={handleSubmit((values) => { //form 에 전송된 값을 values 라는 객체로 변환
          try {
            checkPhoneNumber(values.phoneNumber); //전송된 값 유효성 검사 
            postMyAddress(values) //웹 API 클라이언트 호출
              .then(() => {
                setPostResult("등록됐습니다");
              })
              .catch(() => {
                setPostResult("등록에 실패했습니다");
              });
          } catch (err) {
            if (err instanceof ValidationError) {
              setPostResult("올바르지 않은 값이 포함되어 있습니다");
              return;
            }
            setPostResult("알 수 없는 에러가 발생했습니다");
          }
        })}
      />
      {postResult && <p>{postResult}</p>}
    </div>
  );
};
```

<p align="center">
<img width="482" alt="스크린샷 2024-08-13 02 26 08" src="https://github.com/user-attachments/assets/6c81b762-9979-483d-9df0-a4d7bcfa2c81">
</p>

<br />

>웹 API 응답에 따라 네가지 패턴으로 다른 메시지가 표시되는지 중점적으로 테스트해보자

<br />

### 5.7.2 웹 API 클라이언트 확인
> values로 변환된 값은 Fetch API 를 활용하는 웹 API 클라이언트인 postMyAddress 에서 사용

```shell
postMyAddress 를 활용해서 HTTP 상태가 300번 이상이면 예외 발생
```

```ts
export function postMyAddress(values: unknown): Promise<Result> {
  return fetch(host("/my/address"), {
    method: "POST",
    body: JSON.stringify(values),
    headers,
  }).then(handleResponse);
}
```

<br/>

### 5.7.3  웹 API 클라이언트의 목 함수
> postMyAddress 를 목 객체로 만드는 함수를 작성하려면? (Ch.4)

```ts
import * as Fetchers from ".";
import { httpError, postMyAddressMock } from "./fixtures";

export function mockPostMyAddress(status = 200) {
  if (status > 299) {
    return jest
      .spyOn(Fetchers, "postMyAddress")
      .mockRejectedValueOnce(httpError);
  }
  return jest
    .spyOn(Fetchers, "postMyAddress")
    .mockResolvedValueOnce(postMyAddressMock);
}
```

<br/>

### 5.7.4 입력된 값을 전송하는 인터랙션 함수
> ui 를 조작해서 전송 버튼을 클릭하면 어떤 결과가 나타날까?
>
> 입력란에 모두 입력 후 전송하는 과정 = **비동기 함수** 로 정리

```ts
async function fillValuesAndSubmit() {
  const contactNumber = await inputContactNumber();
  const deliveryAddress = await inputDeliveryAddress();
  const submitValues = { ...contactNumber, ...deliveryAddress };
  await clickSubmit();
  return submitValues;
}
```


<br/>

### 5.7.5 응답 성공 테스트
> 성공하는 패턴의 테스트
>
> mockPostMyAddress 함수를 사용하면 웹 API 클라이언트의 응답이 변경된다.

<br/>

💡 목 모듈을 사용하는 테스트는 파일상단에 jest.mock(모듈 경로); 실행하는 것을 잊지말자! 

```ts
jest.mock("./fetchers");

test("성공하면 '등록됐습니다'가 표시된다", async () => {
  const mockFn = mockPostMyAddress();
  render(<RegisterAddress />);
  const submitValues = await fillValuesAndSubmit();
  expect(mockFn).toHaveBeenCalledWith(expect.objectContaining(submitValues));
  expect(screen.getByText("등록됐습니다")).toBeInTheDocument();
});
```


<br/>

### 5.7.6 응답 실패 테스트
> 웹 API 의 응답이 reject 되는 상황을 재현하고자 목 함수의 인수로 500 설정

```ts
jest.mock("./fetchers");

test("실패하면 '등록에 실패했습니다'가 표시된다", async () => {
  const mockFn = mockPostMyAddress(500);
  render(<RegisterAddress />);
  const submitValues = await fillValuesAndSubmit();
  expect(mockFn).toHaveBeenCalledWith(expect.objectContaining(submitValues));
  expect(screen.getByText("등록에 실패했습니다")).toBeInTheDocument();
});
```

<br/>

### 5.7.7 유효성 검사 오류 테스트
> 전송하려는 값에 대한 유효성 검사를 하면 올바르지 않은 입력값이 포함된 경우에는 전송 자체가 불가능하므로 올바른 값을 입력하도록 도울 수 있다.

```shell
checkPhoneNumber : 전화번호 입력값을 검증하는 유효성 검사 함수
try-catch 문을 통해 err가 validationError의 인스턴스이면 유효성 검사 오류로 간주
```

```ts
<Form
        onSubmit={handleSubmit((values) => {
          try {
            checkPhoneNumber(values.phoneNumber);
            postMyAddress(values)
              .then(() => {
                setPostResult("등록됐습니다");
              })
              .catch(() => {
                setPostResult("등록에 실패했습니다");
              });
          } catch (err) {
            if (err instanceof ValidationError) { //유효성 검사 오류로 간주
              setPostResult("올바르지 않은 값이 포함되어 있습니다");
              return;
            }
            setPostResult("알 수 없는 에러가 발생했습니다");
          }
        })}
      />
```
```ts
export class ValidationError extends Error {}

export function checkPhoneNumber(value: any) {
  if (!value.match(/^[0-9\-]+$/)) {
    throw new ValidationError();
  }
}
```

<br/>

**[ 오류가 발생하도록  올바르지 않은 값으로 변경 후 테스트 ]**

```shell
유효성 검사에서 오류가 발생하도록 fillInvalidValesAndSumbit 을 작성해보자
```
```ts
async function fillInvalidValuesAndSubmit() {
  const contactNumber = await inputContactNumber({
    name: "배언수",
    phoneNumber: "abc-defg-hijkl", //올바르지 않은 값으로 변경
  });
  const deliveryAddress = await inputDeliveryAddress();
  const submitValues = { ...contactNumber, ...deliveryAddress };
  await clickSubmit();
  return submitValues;
}
```

<br />

**[ AAA 패턴 ]**
> 준비 > 실행 > 검증 3잔계로 정리한 가독성이 좋은 테스트 코드

```ts
test("유효성 검사 에러가 발생하면 메시지가 표시된다", async () => {
  render(<RegisterAddress />); //준비
  await fillInvalidValuesAndSubmit(); //실행
  expect(screen.getByText("올바르지 않은 값이 포함되어 있습니다")).toBeInTheDocument(); //검증
});
```

<br/>

### 5.7.8 알 수 없는 오류 테스트
> 목 함수를 실행하지 않은 테스트에서는 웹 API 요청을 처리할 수 없기에 원인 불명의 오류가 발생한다.

```ts
test("원인이 명확하지 않은 에러가 발생하면 메시지가 표시된다", async () => {
  render(<RegisterAddress />);
  await fillValuesAndSubmit();
  expect(screen.getByText("알 수 없는 에러가 발생했습니다")).toBeInTheDocument();
});
});
```

<br/>

---

<br/>


💡 비동기 처리가 있다면 오류 분기가 복잡해지는 상황이 많기에 테스트를 작성하면서 누락된 부분은 없는지 확인해야 한다.


